language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - jruby-18mode
  - jruby-19mode
  - jruby-20mode
  - jruby-21mode
  - jruby-head
  - rbx-2
  - ree
  - ruby-head
matrix:
  include:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
notifications:
  irc:
    channels:
      - irc.freenode.org#rom-rb
    on_success: never
    on_failure: change
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug" # for simplecov
